name: Daily Vaccine Check

on:
  schedule:
    # Runs at 05:45 UTC (08:45 AM Istanbul Time) to avoid traffic jams
    - cron: '45 5 * * *'
  workflow_dispatch: # Allows you to run it manually to test

jobs:
  run-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install libraries
        run: |
          pip install pandas gspread google-auth

      - name: Run Notifier Script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python notifier.py
